//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBikes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentBikesEntities : DbContext
    {
        public RentBikesEntities()
            : base("name=RentBikesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rental_Detail> Rental_Detail { get; set; }
        public virtual DbSet<Rental_Type> Rental_Type { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<Vehicle_Type> Vehicle_Type { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Rental> Rental { get; set; }
    }
}
