//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBikes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_Detail
    {
        public int rentaldetail_id { get; set; }
        public int rental_id { get; set; }
        public int vehicle_id { get; set; }
        public int hours { get; set; }
        public decimal price { get; set; }
        public decimal total { get; set; }
        public int price_id { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
