//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBikes.Core.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Rental
    {
        public Rental()
        {
            this.Rental_Detail = new HashSet<RentalDetail>();
        }

        public int rentalID { get; set; }
        public System.DateTime from { get; set; }
        public System.DateTime to { get; set; }
        public int stateID { get; set; }
        public int stationID { get; set; }
        public int rentaltypeID { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> total { get; set; }
        public int client_id { get; set; }

        public virtual Client Client { get; set; }
        public virtual ICollection<RentalDetail> Rental_Detail { get; set; }
        public virtual RentalType RentalType { get; set; }
        public virtual Station Station { get; set; }
    }
}
