//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBikes.Core.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RentalDetail
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int rentalDetailID { get; set; }
        public int rentalID { get; set; }
        public int vehicleID { get; set; }
        public int hours { get; set; }
        public decimal rentalPrice { get; set; }
        public decimal total { get; set; }
        public int priceID { get; set; }

        public virtual Price Price { get; set; }
        public virtual Rental Rental { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
