//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentBikes.Core.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Rental
    {
        public Rental()
        {
            this.Rental_Detail = new HashSet<RentalDetail>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int rentalID { get; set; }
        public DateTime from { get; set; }
        public DateTime to { get; set; }
        public int stateID { get; set; }
        public int stationID { get; set; }
        public int rentalTypeID { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> total { get; set; }
        public int clientID { get; set; }

        public virtual Client Client { get; set; }
        public virtual ICollection<RentalDetail> Rental_Detail { get; set; }
        public virtual RentalType RentalType { get; set; }
        public virtual Station Station { get; set; }
        public virtual State State { get; set; }
    }
}
